# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f152656f45f80422097e6c7bd1cdd4e9a8f696d9e979a76cf53f094653dee2f99e681bd8cc99d88fb8e96354e3127be5299755caaf356ebc4488ca2e16f28994

test:
  secret_key_base: 342bec538fee281ca57f5dbb82646bcf2628974cc213bf7004936737ae43c57e1cc445957dd32d6659a3a926c35200bd192d9e75dd41feed2a2e0e91984ffc32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
